name: github_graphql_client
description: Minimised reproduction for `flutter/flutter` Issue #96272
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.5
  gql_build: ^0.3.0-alpha+1635885531736
  
